jobs:
- name: build
  plan:
  - get: helm-release
    trigger: true
    params:
      include_source_tarball: true
  - task: build-helm
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: latest
      inputs:
      - name: helm-release
      outputs:
      - name: docker
      run:
        path: bash
        args:
        - -exc
        - |
          curl https://glide.sh/get | sh
          tar -zvxf helm-release/source.tar.gz
          src=$PWD
          target=$PWD/docker

          cd /go
          mkdir -p src/k8s.io
          mv $src/helm-helm-* src/k8s.io/helm
          cd src/k8s.io/helm

          sed -i rootfs/Dockerfile -e's|FROM alpine|FROM arm32v6/alpine|'
          sed -i Makefile -es'/GOARCH=amd64 //'

          export GOARCH=arm
          export GOARM=7

          make bootstrap
          make docker-binary

          cp -v rootfs/* $target/

  - put: tiller-arm-release
    params:
      build: docker
      tag: helm-release/tag
      tag_as_latest: true

resources:
- name: helm-release
  type: github-release
  source:
    owner: helm
    repository: helm
    access_token: ((github.token))
- name: tiller-arm-release
  type: remote-docker-image
  source:
    repository: ((docker.target_arm_tiller))
    tag: latest
    username: ((docker.user_tiller))
    password: ((docker.password_tiller))
    dockerd: ((docker.dockerd))

resource_types:
- name: remote-docker-image
  type: docker-image
  source:
    repository: timotto/docker-image-resource
    tag: latest
  privileged: true
